[server]
headless = true
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#FF8C00"
backgroundColor = "#0A0A0F"
secondaryBackgroundColor = "#121721"
textColor = "#FFFFFF"
font = "sans serif"
